export const palette = {
  primary: '#333333',
  inactive: '#949494',
  text: '#222222',
  red: '#E83A45',
  gray2: '#515151',
  gray3: '#6e6e6e',
  gray4: '#8c8c8c',
  gray5: '#a4a4a4',
  gray6: '#C7C7C7',
  gray7: '#F2F4F7',
  gray8: '#F1F1F1',
  gray9: '#F8F8F8',
  gray200: '#EAECF0',
  transparent: 'transparent',
  white: 'white',
  black: 'black',
  semiTransparentBlack: '#000000CC',
  green: '#10984B',
  green7: '#F2FCF5',
  blue: 'blue',
  blueLight1: '#E8EFFC',
  blurDark1: '#0F468A',
  yellow: '#FFD72D',
  orange: 'orange',
  brow: 'brow',
};

export const Colors = {
  primary: palette.primary,
  inactive: palette.inactive,
  text: palette.text,
  red: palette.red,
  gray2: palette.gray2,
  gray3: palette.gray3,
  gray4: palette.gray4,
  gray5: palette.gray5,
  gray6: palette.gray6,
  gray7: palette.gray7,
  gray8: palette.gray8,
  gray9: palette.gray9,
  gray200: palette.gray200,
  transparent: palette.transparent,
  white: palette.white,
  black: palette.black,
  semiTransparentBlack: palette.semiTransparentBlack,
  green: palette.green,
  green7: palette.green7,
  blue: palette.blue,
  blueLight1: palette.blueLight1,
  blurDark1: palette.blurDark1,
  yellow: palette.yellow,
  orange: palette.orange,
  brow: palette.brow,
};
